### ISSUE TITLE
No site found for link in ReadMe http://iverilog.icarus.com/

### ISSUE THREAD

**Issue by jdwil31401** [steveicarus/iverilog#914] opened 2023-05-03 19:13 UTC
![image](https://user-images.githubusercontent.com/73720642/236020163-19f0bca9-3382-4a5a-9253-d479ef45b55b.png)
[http://iverilog.icarus.com](http://iverilog.icarus.com)

**Comment by martinwhitaker** [comment] 2023-05-03 22:56
Duplicate of #886.

**Closed by martinwhitaker** 2023-05-03 22:56 UTC
