### ISSUE TITLE
Ternary operator with constants 

### ISSUE THREAD

**Issue by 1353369570** [steveicarus/iverilog#879] opened 2023-03-07 08:43 UTC
consider this code：

module top();
   reg expected = 1;
   initial begin
      $display("Const Positive %s", 1 ? "Yes" : "NO");
      $display("Const Negative %s", 0 ? "Yes" : "NO");
      
      $finish;
   end
endmodule

when I am using the  Ubuntu 20.04 release of the iverilog and vvp ，The Const Negative line does not supply the string 'NO'.

$ iverilog -v
Icarus Verilog version 10.3 (stable) ()

Copyright 1998-2015 Stephen Williams

  This program is free software; you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation; either version 2 of the License, or
  (at your option) any later version.
$ iverilog -Wall -g2005-sv 1.v
$ vvp a.out
Const Positive Yes
Const Negative

**Comment by martinwhitaker** [comment] 2023-03-07 09:02
Duplicate of #827. This is fixed in the master branch.

**Closed by martinwhitaker** 2023-03-07 09:02 UTC
