### ISSUE TITLE
Casting to signed bus is not supported.

### ISSUE THREAD

**Issue by bitglitcher** [steveicarus/iverilog#524] opened 2021-06-15 07:21 UTC
Hello, I'm trying to Simulate some code that is synthesizeable. But unfortunately `iverilog` gives me an error.

```
memory_access_tb.sv:158: syntax error
memory_access_tb.sv:158: error: malformed statement
```

Basically is just casting a bus into a signed bus. This works on modelsim and Quartus. But not on `iverilog`.
```verilog
32'(signed'(memory[address[2:0]]))
```
I'm using the `-g2012` flag and my current version of  `iverilog` is: `icarus Verilog version 12.0 (devel) (s20150603-1130-g1f8876be)`

**Comment by bitglitcher** [comment] 2021-06-15 07:37
Are there any alternatives that can be synthesized?

**Comment by martinwhitaker** [comment] 2021-06-15 08:02
Use $signed instead of signed'().
Closing as a duplicate of issue #513.

**Closed by martinwhitaker** 2021-06-15 08:02 UTC
