### ISSUE TITLE
Packed array itterators treated as reg/wire

### ISSUE THREAD

**Issue by hellgate202** [steveicarus/iverilog#1002] opened 2023-09-22 11:40 UTC
```
module iverilog_test #(
   parameter int DATA_WIDTH = 32,
   parameter int KEEP_WIDTH = DATA_WIDTH / 8,
   parameter int PORTS_CNT  = 8
)(
   input                                        clk,
   input        [DATA_WIDTH-1:0]                source,
   output logic [PORTS_CNT-1:0][DATA_WIDTH-1:0] ports
);

always_ff @(posedge clk) begin
   for (int i = 0; i < PORTS_CNT; i++) begin
      for (int j = 0; j < KEEP_WIDTH; j++) begin
         ports[i][j * 8 +: 8] <= source[j * 8 +: 8];
      end
   end
end

endmodule
```
For this code an error is risen, that wire/reg 'i' cannot be an array index
```
iverilog_test.sv:14: error: A reference to a wire or reg (`i') is not allowed in a constant expression.
iverilog_test.sv:14: error: Array index expressions must be constant here.
iverilog_test.sv:14: assert: elab_lval.cc:933: failed assertion rc
Aborted (core dumped)
```

**Comment by larsclausen** [comment] 2023-09-22 15:27
This is a duplicate of #521. Using a variable index for anything but the last dimension in an array is currently not supported.

**Closed** 2023-09-22 20:07 UTC
