### ISSUE TITLE
SV queues inside classes

### ISSUE THREAD

**Issue by apseng03** [steveicarus/iverilog#293] opened 2020-01-01 13:00 UTC
Hi,
I am trying to port pieces of UVM into Icarus. While trying Command-Line Processor, I am getting the following error. Is it possible to support this, please?
Thanks,
Ani

*Command*: iverilog -g2012 sv_queues.sv

*Error*: sv_queues.sv:5: sorry: SV queues inside classes are not yet supported.

*Code*:
class uvm_report_object;
endclass : uvm_report_object

class uvm_cmdline_processor extends uvm_report_object;
  protected string m_plus_argv[$];
  function void get_plusargs (output string args[$]);
    args = m_plus_argv;
  endfunction
endclass : uvm_cmdline_processor
module top;
endmodule : top

**Comment by martinwhitaker** [comment] 2020-01-04 23:12
Duplicate of issue #192

**Closed by martinwhitaker** 2020-01-04 23:12 UTC
