### ISSUE TITLE
Does icarus give up supporting the SV interface syntax?

### ISSUE THREAD

**Issue by Superchao-ai** [steveicarus/iverilog#963] opened 2023-06-27 04:01 UTC
Does icarus give up supporting the SV interface syntax?
I tried to compile the following code：
```verilog
//my_interface.v
interface ral_bkdr_interface;
logic rst;
endinterface
```
Received the following feedback
```log
my_interface.v:1: syntax error
I give up.
```

**Comment by UweBonnes** [comment] 2023-06-27 13:08
This is a duplicate of #464.

I had a glance at parse.y, and a lot around interface, modport and friends is alredy available. It would be wonderful is some person with more knowledge could comment or even have a look.

**Closed** 2023-06-28 14:53 UTC
Labels: Obsolete
