### ISSUE TITLE
During simulation, iverilog mistakenly assigned a value to an undriven variable.

### ISSUE THREAD

**Issue by llb-del** [steveicarus/iverilog#1156] opened 2024-08-06 12:33 UTC
We are practicing the basic function of' verilog', so we use three different tools,' iverilog',' vivado' and' quartus', to simulate the same comprehensive file' Subsystem.v' to verify the simulation results of our model. Theoretically, the same verilog project should have the same simulation results in three different simulation tools, but we found that the results were not the same after verification. Among them, the simulation results of' vivado' and' quartus' are consistent, while' iverilog' is inconsistent with the simulation results of the other two tools.
![658efd3063241d94f25f31c89d64dc33](https://github.com/user-attachments/assets/95973be8-a65d-490b-8802-44d5fed552e2)
`quarters`simulation results.
![0694a6a9dd4f88e560410d200f5cdcb2](https://github.com/user-attachments/assets/afc68311-b4db-443c-ba74-be4041f54b62)
`iverilog`simulation results.
![f90e3b1c07774a3c74c913feb8021b41](https://github.com/user-attachments/assets/d9ea9108-6d85-45d2-b118-eeeaa28d6fa1)
`vivado`simulation results.

Specifically, as shown in the following figure, the difference lies in' 0ns-100ns'. It can be clearly seen in the tools of' vivado' and' quartus' that the assignment of' hdl_out' is' x', while in' 0ns-50ns', a fixed value is given in the tool of' iverilog', and after '50ns', it is. Iverilog' seems to have incorrectly assigned a variable that is not driven. Currently for the same.

Our source files are as follows, in which Subsystem.v is our main file.
[source.zip](https://github.com/user-attachments/files/16510248/source.zip)

**Comment by martinwhitaker** [comment] 2024-08-06 21:30
This is suspiciously similar to #1151. Is this a training course exercise?

You should try to reduce the code to the simplest test case that still reproduces the issue, and then look for race conditions in the code.

**Comment by caryr** [comment] 2024-08-07 03:15
The source file you uploaded is not a zip file.

**Comment by caryr** [comment] 2024-08-26 13:54
See #1161 where I have confirmed this is not an issue in Icarus using that code. Since this is not a complete example I am closing this ticket.

**Closed by caryr** 2024-08-26 13:54 UTC
Labels: Need info
