### ISSUE TITLE
The sv_interface test is not implemented

### ISSUE THREAD

**Issue by steveicarus** [steveicarus/iverilog#1081] opened 2024-01-21 03:03 UTC
This test is marked as NI since is generates compiler errors. The test is in ivtest/ivltests/sv_interface.v.

```
steve@icarus:~/icarus/eda/devel/verilog/ivtest> cat log/sv_interface-iverilog-stderr.log 
ivltests/sv_interface.v:119: syntax error
ivltests/sv_interface.v:1: Errors in port declarations.
ivltests/sv_interface.v:151: syntax error
ivltests/sv_interface.v:1: Errors in port declarations.
```

**Comment by caryr** [comment] 2024-01-23 02:04
I believe interfaces are not fully implemented.

**Comment by caryr** [comment] 2024-01-23 02:21
This is a duplicate of #166 so closing this and adding the test to the previous PR

**Closed by caryr** 2024-01-23 02:21 UTC
Labels: Enhancement
