### ISSUE TITLE
Help Wanted: no output file for vvp generated in powershell

### ISSUE THREAD

**Issue by zhang-stephen** [steveicarus/iverilog#933] opened 2023-06-11 03:44 UTC
ENV:
 - Windows 11 23H2
 - Powershell 7.2
 - iverilog 11.0, installed by msys2

I am playing with iverilog for some simple simulation. And I am trying the example provided [here](https://steveicarus.github.io/iverilog/usage/gtkwave.html).

Then I got nothing when I ran `iverilog -o dsn counter_tb.v counter.v` in powershell, but got valid output in msys2 shell.

Is the powershell or Command Prompt not supported yet? Any suggestions?

BTW, is Windonws Subsystem of Linux(WSL) supported?

**Comment by caryr** [comment] 2023-06-11 05:39
We do not provide Windows binaries and have limited experience on Windows in general so I'm not certain how much we can help. In the past I have used cygwin to compile and run on Windows. WSL should work, but I'm not certain it will support GTKWave.

**Comment by martinwhitaker** [comment] 2023-06-11 08:21
Last time I checked, it worked when using the Windows Command Prompt. But you need to make sure the MSYS2 DLLs used by iverilog are on the Windows search path or have been copied into the same directory as iverilog.exe.

**Comment by caryr** [comment] 2023-06-15 21:17
Were you able to resolve this issue? This appears to be a configuration/setup issue and not a bug in Icarus.

**Comment by zhang-stephen** [comment] 2023-06-24 15:06
I cannot got correct output in powershell yet, but it works well in cmd.

**Comment by caryr** [comment] 2023-09-04 02:02
No more information provided so closing this report.

**Closed by caryr** 2023-09-04 02:02 UTC
Labels: Need info

**Comment by DvvCz** [comment] 2023-10-26 20:25
Yeah seems WSL does not give any output either. I downloaded through `sudo apt install iverilog` and `vvp` said it was version 11.

Works fine with regular windows terminal (v12 - https://bleyer.org/icarus), just an inconvenience since I'm trying to test my script to use icarus verilog for continuous integration on github.

Attaching necessary files and output in case you want to pursue this, specific (system) verilog code likely does not matter.

``src/FLC.sv``
```verilog
module FLC (input FLC_A, input FLC_B, input FLC_C, output FLC_Q);
	assign FLC_Q = (FLC_B & FLC_C) | ~(FLC_A | FLC_B);
endmodule
```

``tests/FLC_TB.sv``
```verilog
`timescale 1ns / 1ps

`include "../src/FLC.sv"

module FLC_TB ();

	reg flc_a;
	reg flc_b;
	reg flc_c;

	wire flc_q;

	FLC dut (
		.FLC_A (flc_a),
		.FLC_B (flc_b),
		.FLC_C (flc_c),
		.FLC_Q (flc_q)
	);

	initial begin
		flc_a = 0; flc_b = 0; flc_c = 0;
		#10 if (flc_q != 1) $error("0, 0, 0 != 1");

		flc_a = 0; flc_b = 0; flc_c = 1;
		#10 if (flc_q != 1) $error("0, 0, 1 != 1");

		flc_a = 0; flc_b = 1; flc_c = 0;
		#10 if (flc_q != 0) $error("0, 1, 0 != 0");

		flc_a = 0; flc_b = 1; flc_c = 1;
		#10 if (flc_q != 1) $error("0, 1, 1 != 1");

		flc_a = 1; flc_b = 0; flc_c = 0;
		#10 if (flc_q != 0) $error("1, 0, 0 != 0");

		flc_a = 1; flc_b = 0; flc_c = 1;
		#10 if (flc_q != 0) $error("1, 0, 1 != 0");

		flc_a = 1; flc_b = 1; flc_c = 0;
		#10 if (flc_q != 0) $error("1, 1, 0 != 0");

		flc_a = 1; flc_b = 1; flc_c = 1;
		#10 if (flc_q != 1) $error("1, 1, 1 != 1");

		$finish;
	end

endmodule
```

```
iverilog -g2012 -Isrc -o temp tests/FLC_TB.sv
```

`temp`
```
#! /usr/bin/vvp
:ivl_version "11.0 (stable)";
:ivl_delay_selection "TYPICAL";
:vpi_time_precision - 12;
:vpi_module "/usr/lib/x86_64-linux-gnu/ivl/system.vpi";
:vpi_module "/usr/lib/x86_64-linux-gnu/ivl/vhdl_sys.vpi";
:vpi_module "/usr/lib/x86_64-linux-gnu/ivl/vhdl_textio.vpi";
:vpi_module "/usr/lib/x86_64-linux-gnu/ivl/v2005_math.vpi";
:vpi_module "/usr/lib/x86_64-linux-gnu/ivl/va_math.vpi";
:vpi_module "/usr/lib/x86_64-linux-gnu/ivl/v2009.vpi";
S_0x55a297b290b0 .scope package, "$unit" "$unit" 2 1;
 .timescale 0 0;
S_0x55a297b3b4f0 .scope module, "FLC_TB" "FLC_TB" 3 5;
 .timescale -9 -12;
v0x55a297b547d0_0 .var "flc_a", 0 0;
v0x55a297b54890_0 .var "flc_b", 0 0;
v0x55a297b54960_0 .var "flc_c", 0 0;
v0x55a297b54a60_0 .net "flc_q", 0 0, L_0x55a297b54df0;  1 drivers
S_0x55a297b3b680 .scope module, "dut" "FLC" 3 13, 4 1 0, S_0x55a297b3b4f0;
 .timescale -9 -12;
    .port_info 0 /INPUT 1 "FLC_A";
    .port_info 1 /INPUT 1 "FLC_B";
    .port_info 2 /INPUT 1 "FLC_C";
    .port_info 3 /OUTPUT 1 "FLC_Q";
L_0x55a297b54b30 .functor AND 1, v0x55a297b54890_0, v0x55a297b54960_0, C4<1>, C4<1>;
L_0x55a297b54c70 .functor OR 1, v0x55a297b547d0_0, v0x55a297b54890_0, C4<0>, C4<0>;
L_0x55a297b54d30 .functor NOT 1, L_0x55a297b54c70, C4<0>, C4<0>, C4<0>;
L_0x55a297b54df0 .functor OR 1, L_0x55a297b54b30, L_0x55a297b54d30, C4<0>, C4<0>;
v0x55a297b2cd50_0 .net "FLC_A", 0 0, v0x55a297b547d0_0;  1 drivers
v0x55a297b54210_0 .net "FLC_B", 0 0, v0x55a297b54890_0;  1 drivers
v0x55a297b542d0_0 .net "FLC_C", 0 0, v0x55a297b54960_0;  1 drivers
v0x55a297b543a0_0 .net "FLC_Q", 0 0, L_0x55a297b54df0;  alias, 1 drivers
v0x55a297b54460_0 .net *"_ivl_0", 0 0, L_0x55a297b54b30;  1 drivers
v0x55a297b54590_0 .net *"_ivl_2", 0 0, L_0x55a297b54c70;  1 drivers
v0x55a297b54670_0 .net *"_ivl_4", 0 0, L_0x55a297b54d30;  1 drivers
    .scope S_0x55a297b3b4f0;
T_0 ;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x55a297b547d0_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x55a297b54890_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x55a297b54960_0, 0, 1;
    %delay 10000, 0;
    %load/vec4 v0x55a297b54a60_0;
    %pad/u 32;
    %cmpi/ne 1, 0, 32;
    %jmp/0xz  T_0.0, 4;
    %vpi_call/w 3 22 "$error", "0, 0, 0 != 1" {0 0 0};
T_0.0 ;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x55a297b547d0_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x55a297b54890_0, 0, 1;
    %pushi/vec4 1, 0, 1;
    %store/vec4 v0x55a297b54960_0, 0, 1;
    %delay 10000, 0;
    %load/vec4 v0x55a297b54a60_0;
    %pad/u 32;
    %cmpi/ne 1, 0, 32;
    %jmp/0xz  T_0.2, 4;
    %vpi_call/w 3 25 "$error", "0, 0, 1 != 1" {0 0 0};
T_0.2 ;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x55a297b547d0_0, 0, 1;
    %pushi/vec4 1, 0, 1;
    %store/vec4 v0x55a297b54890_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x55a297b54960_0, 0, 1;
    %delay 10000, 0;
    %load/vec4 v0x55a297b54a60_0;
    %pad/u 32;
    %cmpi/ne 0, 0, 32;
    %jmp/0xz  T_0.4, 4;
    %vpi_call/w 3 28 "$error", "0, 1, 0 != 0" {0 0 0};
T_0.4 ;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x55a297b547d0_0, 0, 1;
    %pushi/vec4 1, 0, 1;
    %store/vec4 v0x55a297b54890_0, 0, 1;
    %pushi/vec4 1, 0, 1;
    %store/vec4 v0x55a297b54960_0, 0, 1;
    %delay 10000, 0;
    %load/vec4 v0x55a297b54a60_0;
    %pad/u 32;
    %cmpi/ne 1, 0, 32;
    %jmp/0xz  T_0.6, 4;
    %vpi_call/w 3 31 "$error", "0, 1, 1 != 1" {0 0 0};
T_0.6 ;
    %pushi/vec4 1, 0, 1;
    %store/vec4 v0x55a297b547d0_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x55a297b54890_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x55a297b54960_0, 0, 1;
    %delay 10000, 0;
    %load/vec4 v0x55a297b54a60_0;
    %pad/u 32;
    %cmpi/ne 0, 0, 32;
    %jmp/0xz  T_0.8, 4;
    %vpi_call/w 3 34 "$error", "1, 0, 0 != 0" {0 0 0};
T_0.8 ;
    %pushi/vec4 1, 0, 1;
    %store/vec4 v0x55a297b547d0_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x55a297b54890_0, 0, 1;
    %pushi/vec4 1, 0, 1;
    %store/vec4 v0x55a297b54960_0, 0, 1;
    %delay 10000, 0;
    %load/vec4 v0x55a297b54a60_0;
    %pad/u 32;
    %cmpi/ne 0, 0, 32;
    %jmp/0xz  T_0.10, 4;
    %vpi_call/w 3 37 "$error", "1, 0, 1 != 0" {0 0 0};
T_0.10 ;
    %pushi/vec4 1, 0, 1;
    %store/vec4 v0x55a297b547d0_0, 0, 1;
    %pushi/vec4 1, 0, 1;
    %store/vec4 v0x55a297b54890_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x55a297b54960_0, 0, 1;
    %delay 10000, 0;
    %load/vec4 v0x55a297b54a60_0;
    %pad/u 32;
    %cmpi/ne 0, 0, 32;
    %jmp/0xz  T_0.12, 4;
    %vpi_call/w 3 40 "$error", "1, 1, 0 != 0" {0 0 0};
T_0.12 ;
    %pushi/vec4 1, 0, 1;
    %store/vec4 v0x55a297b547d0_0, 0, 1;
    %pushi/vec4 1, 0, 1;
    %store/vec4 v0x55a297b54890_0, 0, 1;
    %pushi/vec4 1, 0, 1;
    %store/vec4 v0x55a297b54960_0, 0, 1;
    %delay 10000, 0;
    %load/vec4 v0x55a297b54a60_0;
    %pad/u 32;
    %cmpi/ne 1, 0, 32;
    %jmp/0xz  T_0.14, 4;
    %vpi_call/w 3 43 "$error", "1, 1, 1 != 1" {0 0 0};
T_0.14 ;
    %vpi_call/w 3 45 "$finish" {0 0 0};
    %end;
    .thread T_0;
# The file index is used to find the file name in the following table.
:file_names 5;
    "N/A";
    "<interactive>";
    "-";
    "tests/FLC_TB.sv";
    "src/../src/FLC.sv";
```

Equivalent windows output:
```
#! /c/Source/iverilog-install/bin/vvp
:ivl_version "12.0 (devel)" "(s20150603-1539-g2693dd32b)";
:ivl_delay_selection "TYPICAL";
:vpi_time_precision - 12;
:vpi_module "D:\Programs\iverilog\lib\ivl\system.vpi";
:vpi_module "D:\Programs\iverilog\lib\ivl\vhdl_sys.vpi";
:vpi_module "D:\Programs\iverilog\lib\ivl\vhdl_textio.vpi";
:vpi_module "D:\Programs\iverilog\lib\ivl\v2005_math.vpi";
:vpi_module "D:\Programs\iverilog\lib\ivl\va_math.vpi";
:vpi_module "D:\Programs\iverilog\lib\ivl\v2009.vpi";
S_000001f3555e9fb0 .scope package, "$unit" "$unit" 2 1;
 .timescale 0 0;
S_000001f3555ea140 .scope module, "FLC_TB" "FLC_TB" 3 5;
 .timescale -9 -12;
v000001f35580f8f0_0 .var "flc_a", 0 0;
v000001f35580f990_0 .var "flc_b", 0 0;
v000001f35580fa30_0 .var "flc_c", 0 0;
v000001f35580fad0_0 .net "flc_q", 0 0, L_000001f3557ca750;  1 drivers
S_000001f3557c50f0 .scope module, "dut" "FLC" 3 13, 4 1 0, S_000001f3555ea140;
 .timescale -9 -12;
    .port_info 0 /INPUT 1 "FLC_A";
    .port_info 1 /INPUT 1 "FLC_B";
    .port_info 2 /INPUT 1 "FLC_C";
    .port_info 3 /OUTPUT 1 "FLC_Q";
L_000001f3557ca360 .functor AND 1, v000001f35580f990_0, v000001f35580fa30_0, C4<1>, C4<1>;
L_000001f3557ca280 .functor OR 1, v000001f35580f8f0_0, v000001f35580f990_0, C4<0>, C4<0>;
L_000001f3557ca520 .functor NOT 1, L_000001f3557ca280, C4<0>, C4<0>, C4<0>;
L_000001f3557ca750 .functor OR 1, L_000001f3557ca360, L_000001f3557ca520, C4<0>, C4<0>;
v000001f355792df0_0 .net "FLC_A", 0 0, v000001f35580f8f0_0;  1 drivers
v000001f355792970_0 .net "FLC_B", 0 0, v000001f35580f990_0;  1 drivers
v000001f3557c5280_0 .net "FLC_C", 0 0, v000001f35580fa30_0;  1 drivers
v000001f3557c5320_0 .net "FLC_Q", 0 0, L_000001f3557ca750;  alias, 1 drivers
v000001f3557c53c0_0 .net *"_ivl_0", 0 0, L_000001f3557ca360;  1 drivers
v000001f3557c5460_0 .net *"_ivl_2", 0 0, L_000001f3557ca280;  1 drivers
v000001f35580f850_0 .net *"_ivl_4", 0 0, L_000001f3557ca520;  1 drivers
    .scope S_000001f3555ea140;
T_0 ;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v000001f35580f8f0_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v000001f35580f990_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v000001f35580fa30_0, 0, 1;
    %delay 10000, 0;
    %load/vec4 v000001f35580fad0_0;
    %pad/u 32;
    %cmpi/ne 1, 0, 32;
    %jmp/0xz  T_0.0, 4;
    %vpi_call/w 3 22 "$error", "0, 0, 0 != 1" {0 0 0};
T_0.0 ;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v000001f35580f8f0_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v000001f35580f990_0, 0, 1;
    %pushi/vec4 1, 0, 1;
    %store/vec4 v000001f35580fa30_0, 0, 1;
    %delay 10000, 0;
    %load/vec4 v000001f35580fad0_0;
    %pad/u 32;
    %cmpi/ne 1, 0, 32;
    %jmp/0xz  T_0.2, 4;
    %vpi_call/w 3 25 "$error", "0, 0, 1 != 1" {0 0 0};
T_0.2 ;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v000001f35580f8f0_0, 0, 1;
    %pushi/vec4 1, 0, 1;
    %store/vec4 v000001f35580f990_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v000001f35580fa30_0, 0, 1;
    %delay 10000, 0;
    %load/vec4 v000001f35580fad0_0;
    %pad/u 32;
    %cmpi/ne 0, 0, 32;
    %jmp/0xz  T_0.4, 4;
    %vpi_call/w 3 28 "$error", "0, 1, 0 != 0" {0 0 0};
T_0.4 ;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v000001f35580f8f0_0, 0, 1;
    %pushi/vec4 1, 0, 1;
    %store/vec4 v000001f35580f990_0, 0, 1;
    %pushi/vec4 1, 0, 1;
    %store/vec4 v000001f35580fa30_0, 0, 1;
    %delay 10000, 0;
    %load/vec4 v000001f35580fad0_0;
    %pad/u 32;
    %cmpi/ne 1, 0, 32;
    %jmp/0xz  T_0.6, 4;
    %vpi_call/w 3 31 "$error", "0, 1, 1 != 1" {0 0 0};
T_0.6 ;
    %pushi/vec4 1, 0, 1;
    %store/vec4 v000001f35580f8f0_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v000001f35580f990_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v000001f35580fa30_0, 0, 1;
    %delay 10000, 0;
    %load/vec4 v000001f35580fad0_0;
    %pad/u 32;
    %cmpi/ne 0, 0, 32;
    %jmp/0xz  T_0.8, 4;
    %vpi_call/w 3 34 "$error", "1, 0, 0 != 0" {0 0 0};
T_0.8 ;
    %pushi/vec4 1, 0, 1;
    %store/vec4 v000001f35580f8f0_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v000001f35580f990_0, 0, 1;
    %pushi/vec4 1, 0, 1;
    %store/vec4 v000001f35580fa30_0, 0, 1;
    %delay 10000, 0;
    %load/vec4 v000001f35580fad0_0;
    %pad/u 32;
    %cmpi/ne 0, 0, 32;
    %jmp/0xz  T_0.10, 4;
    %vpi_call/w 3 37 "$error", "1, 0, 1 != 0" {0 0 0};
T_0.10 ;
    %pushi/vec4 1, 0, 1;
    %store/vec4 v000001f35580f8f0_0, 0, 1;
    %pushi/vec4 1, 0, 1;
    %store/vec4 v000001f35580f990_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v000001f35580fa30_0, 0, 1;
    %delay 10000, 0;
    %load/vec4 v000001f35580fad0_0;
    %pad/u 32;
    %cmpi/ne 0, 0, 32;
    %jmp/0xz  T_0.12, 4;
    %vpi_call/w 3 40 "$error", "1, 1, 0 != 0" {0 0 0};
T_0.12 ;
    %pushi/vec4 1, 0, 1;
    %store/vec4 v000001f35580f8f0_0, 0, 1;
    %pushi/vec4 1, 0, 1;
    %store/vec4 v000001f35580f990_0, 0, 1;
    %pushi/vec4 1, 0, 1;
    %store/vec4 v000001f35580fa30_0, 0, 1;
    %delay 10000, 0;
    %load/vec4 v000001f35580fad0_0;
    %pad/u 32;
    %cmpi/ne 1, 0, 32;
    %jmp/0xz  T_0.14, 4;
    %vpi_call/w 3 43 "$error", "1, 1, 1 != 1" {0 0 0};
T_0.14 ;
    %vpi_call/w 3 45 "$finish" {0 0 0};
    %end;
    .thread T_0;
# The file index is used to find the file name in the following table.
:file_names 5;
    "N/A";
    "<interactive>";
    "-";
    "tests/FLC_TB.sv";
    "src/../src/FLC.sv";
```
