### ISSUE TITLE
Syntax error for .vh file that only contains binary number.

### ISSUE THREAD

**Issue by wxbbuaa2011** [steveicarus/iverilog#238] opened 2019-04-21 07:58 UTC
iverilog -o dd -c file.list
include/pu_controller_bin.vh:1: syntax error
I give up.
But this file is a binary file, and other similar files have no syntax errors.

**Comment by wxbbuaa2011** [comment] 2019-04-21 08:16
The file pu_controller_bin.vh only contains  0000000000000000000000000000011011000000001000000000000000000000000000010011. But it  produces a syntax error.

**Comment by martinwhitaker** [comment] 2019-04-21 17:13
That's correct. A sequence of binary digits on its own is not valid Verilog.

**Comment by martinwhitaker** [comment] 2019-07-24 10:14
Not a bug, so closing.

**Closed by martinwhitaker** 2019-07-24 10:14 UTC
