### ISSUE TITLE
Function arguments by name: syntax error

### ISSUE THREAD

**Issue by logicmonkey** [steveicarus/iverilog#702] opened 2022-04-25 13:30 UTC
For functions with many arguments it would be nice if we could pass them by name.  This greatly enhances code readability.

```
% iverilog -g2012 argbynamebug.sv
argbynamebug.sv:15: syntax error
argbynamebug.sv:15: error: malformed statement
```

```
module argbynamebug;

function automatic logic [3:0] sum(logic [3:0] a, logic [3:0] b);
begin
  return a + b;
end
endfunction

initial begin
  logic [3:0] my_a, my_b, my_y;

  my_a = 4'd5;
  my_b = 4'd3;

  my_y = sum(.a(my_a), .b(my_b)); // arguments by name: syntax error
  //my_y = sum(my_a, my_b);      // positional OK

  $display("%d", my_y);
  $finish();
end

endmodule
```

**Comment by martinwhitaker** [comment] 2022-04-25 18:19
Duplicate of issue #233.

**Closed by martinwhitaker** 2022-04-25 18:19 UTC
